service: MyRestservice

package:
  individually: true
  exclude:
    - ./**

provider:
      name: aws
      runtime: go1.x
      region: us-east-1

      environment:
        DEVICES_TABLE_NAME: ${self:custom.devicesTableName}
      iamRoleStatements: #Defines what other AWS services out lambda function can access
        - Effect: Allow # Allow access to DynamoDB tables
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - ${self:custom.devicesTableArn}

functions:
  createitem:
    handler: ./bin/handlers/create
    package:
      include:
        - ./bin/handlers/create
    events:
      - http:
          path: /devices
          method: post
          cors: true

  list:
    handler: ./bin/handlers/list
    package:
      include:
        - ./bin/handlers/list
    events:
      - http:
          path: /devices
          method: get
          cors: true

  getitem:
      handler: ./bin/handlers/get
      package:
        include:
            - ./bin/handlers/get
      events:
        - http:
            path: /devices/{id}
            method: get
            cors: true


  deleteitem:
      handler: ./bin/handlers/delete
      package:
        include:
            - ./bin/handlers/delete
      events:
        - http:
            path: /devices/{id}
            method: delete
            cors: true


custom:
  devicesTableName: Devices
  devicesTableArn:  #ARN are addresses of deployed services in AWS space
    Fn::Join:
      - ":"
      - - arn
        - aws
        - dynamodb
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - table/${self:custom.devicesTableName}

resource:
  Resource: #Supporting Aws services
    DevicesDynamoDBTable: #Define a new DynamoDB Table resource to store device info
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.devicesTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
